/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Pranit Bankar
 */
import java.lang.String;

public class LibraryFrame extends javax.swing.JFrame {
    Book[] A = new Book[100];
    int book_counter=0;
    boolean add_book=false;
    boolean find_book=false;
    String temp_Name,temp_Author,temp_Publisher,temp_PublicationYear;
    int temp_Position=0;
    int[] Searching=new int[100];
    
    for(int k=0;k<100;k++)
    {
        Searching[k]=-1;
    }
    
    void display_Book(Book a)
    {
        Name_Book.setText(a.Name);
        Author_Book.setText(a.Author);
        Publisher_Book.setText(a.Publisher);
        PublicationYear_Book.setText(a.PublicationYear);
        Position_Book.setText(Integer.toString(a.Position));
    }
    /**
     * Creates new form LibraryFrame
     */
    public LibraryFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title_Frame = new javax.swing.JLabel();
        Add_Book = new javax.swing.JRadioButton();
        Find_Book = new javax.swing.JRadioButton();
        Confirm_Book = new javax.swing.JButton();
        Position_Book = new javax.swing.JTextField();
        Operation_Summary = new javax.swing.JTextField();
        Name_Book = new javax.swing.JTextField();
        Publisher_Book = new javax.swing.JTextField();
        Author_Book = new javax.swing.JTextField();
        PublicationYear_Book = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title_Frame.setText("Virtual Library");

        Add_Book.setText("Add a Book");
        Add_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_BookActionPerformed(evt);
            }
        });

        Find_Book.setText("Find a Book");
        Find_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Find_BookActionPerformed(evt);
            }
        });

        Confirm_Book.setText("Confirm");
        Confirm_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confirm_BookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(Title_Frame))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Name_Book)
                            .addComponent(Add_Book)
                            .addComponent(Publisher_Book, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Find_Book)
                    .addComponent(PublicationYear_Book)
                    .addComponent(Author_Book, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Position_Book, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Confirm_Book, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Operation_Summary))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_Frame)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name_Book, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Author_Book, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Publisher_Book, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PublicationYear_Book, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Position_Book, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Find_Book)
                    .addComponent(Add_Book))
                .addGap(5, 5, 5)
                .addComponent(Confirm_Book)
                .addGap(18, 18, 18)
                .addComponent(Operation_Summary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_BookActionPerformed
        add_book = true;
    }//GEN-LAST:event_Add_BookActionPerformed

    private void Find_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Find_BookActionPerformed
        find_book = true;
    }//GEN-LAST:event_Find_BookActionPerformed

    private void Confirm_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirm_BookActionPerformed
        if(add_book==true)
        {
            temp_Name=Name_Book.getText();
            temp_Author=Author_Book.getText();
            temp_Publisher=Publisher_Book.getText();
            temp_PublicationYear=PublicationYear_Book.getText();
            
            A[book_counter]=new Book(temp_Name,temp_Author,temp_Publisher,temp_PublicationYear,book_counter);
            book_counter+=1;
        }
        if(find_book==true)
        {
            if(Position_Book.getText()!=null)
                {
                    temp_Position=Integer.parseInt(Position_Book.getText());
                    display_Book(A[temp_Position]);
                }
            else{
            temp_Name=Name_Book.getText();
            temp_Author=Author_Book.getText();
            temp_Publisher=Publisher_Book.getText();
            temp_PublicationYear=PublicationYear_Book.getText();
            
                int findName=0;
                int findAuthor=0;
                int findPublisher=0;
                int findPublicationYear=0;)
            for(int i=0;i<=book_counter;i+=1)
            {
            boolean searching=(temp_Name!=null && (A[i].Name.equals(temp_Name))==true)
                             || (temp_Author!=null && (A[i].Author.equals(temp_Author))==true)
                             || (temp_Publisher!=null && (A[i].Publisher.equals(temp_Publisher))==true)
                             || (temp_PublicationYear!=null && (A[i].PublicationYear.equals(temp_PublicationYear))==true
             if(searching)
             {
                 Searching[temp_Position]=i;
                 temp_Position+=1;
             }
            }
            if(temp_Position>1)
            {Operation_Summary.setText("Books are at positions:\n"for(int element:Searching) {Integer.toString(element)+" "} );}
            else {display_Book(Searching[0]);}
            }
        }
    }//GEN-LAST:event_Confirm_BookActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Add_Book;
    private javax.swing.JTextField Author_Book;
    private javax.swing.JButton Confirm_Book;
    private javax.swing.JRadioButton Find_Book;
    private javax.swing.JTextField Name_Book;
    private javax.swing.JTextField Operation_Summary;
    private javax.swing.JTextField Position_Book;
    private javax.swing.JTextField PublicationYear_Book;
    private javax.swing.JTextField Publisher_Book;
    private javax.swing.JLabel Title_Frame;
    // End of variables declaration//GEN-END:variables

